name: Sync Docs

on:
  # 允许手动push触发
  push:
   branches:
     - main
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@master

      - name: 安装node环境
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: 安装依赖
        run: |
          export TZ='Asia/Shanghai'
          npm install @elog/cli -g

      - name: 同步文档
        env:
          FLOWUS_TABLE_PAGE_ID: ${{ secrets.FLOWUS_TABLE_PAGE_ID }}
          HALO_ENDPOINT: ${{ secrets.HALO_ENDPOINT }}
          HALO_TOKEN: ${{ secrets.HALO_TOKEN }}
          HALO_POLICY_NAME: ${{ secrets.HALO_POLICY_NAME }}
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
          ELOG_GITHUB_USER: ${{ secrets.ELOG_GITHUB_USER }}
          ELOG_GITHUB_REPO: ${{ secrets.ELOG_GITHUB_REPO }}
        run: |
          elog sync

      - name: 配置Git用户名邮箱
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 提交更新记录到GitHub仓库
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "Refresh elog.cache.json" -a

      - name: 推送更新到仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
