name: Sync Docs

on:
  # 允许手动push触发
  push:
   branches:
     - main
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v4

      - name: 安装node环境
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: 安装依赖
        run: |
          export TZ='Asia/Shanghai'
          npm install @elog/cli -g

      - name: 同步文档
        env:
          FLOWUS_TABLE_PAGE_ID: ${{ secrets.FLOWUS_TABLE_PAGE_ID }}
          HALO_ENDPOINT: ${{ secrets.HALO_ENDPOINT }}
          HALO_TOKEN: ${{ secrets.HALO_TOKEN }}
          HALO_POLICY_NAME: ${{ secrets.HALO_POLICY_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELOG_GITHUB_USER: ${{ secrets.ELOG_GITHUB_USER }}
          ELOG_GITHUB_REPO: ${{ secrets.ELOG_GITHUB_REPO }}
        run: |
          elog sync

      - name: 上传缓存到Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: "true"
          name: "同步缓存"
          tag: "latest"
          artifacts: "elog.cache.json,elog.config.js"
          token: ${{ secrets.GITHUB_TOKEN }}